import i1 from '../../assets/images/1.png';
import i2 from '../../assets/images/2.png';
import i3 from '../../assets/images/3.png';
import i4 from '../../assets/images/4.png';
import i5 from '../../assets/images/5.png';
import i6 from '../../assets/images/6.png';
import i7 from '../../assets/images/7.png';
import i8 from '../../assets/images/8.png';
import i9 from '../../assets/images/9.png';
import i10 from '../../assets/images/10.png';
import i11 from '../../assets/images/11.png';
import i12 from '../../assets/images/12.png';
import i13 from '../../assets/images/13.png';
import i14 from '../../assets/images/14.png';
import i15 from '../../assets/images/15.png';
import i17 from '../../assets/images/17.png';
import i18 from '../../assets/images/18.png';
import i20 from '../../assets/images/20.png';
import i21 from '../../assets/images/21.png';
import i22 from '../../assets/images/22.png';

export const images: string[] = [i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11, i12, i13, i14, i15,  i17, i18, i20, i21, i22];
