import i0 from '../../assets/images/0.png';
import i1 from '../../assets/images/1.png';
import i2 from '../../assets/images/2.png';
import i3 from '../../assets/images/3.png';
import i4 from '../../assets/images/4.png';
import i5 from '../../assets/images/5.png';
import i6 from '../../assets/images/6.png';
import i7 from '../../assets/images/7.png';
import i8 from '../../assets/images/8.png';
import i9 from '../../assets/images/9.png';
import i10 from '../../assets/images/10.png';
import i11 from '../../assets/images/11.png';
import i12 from '../../assets/images/12.png';
import i13 from '../../assets/images/13.png';
import i14 from '../../assets/images/14.png';
import i15 from '../../assets/images/15.png';
import i16 from '../../assets/images/16.png';
import i17 from '../../assets/images/17.png';
import i18 from '../../assets/images/18.png';
import i19 from '../../assets/images/19.png';
import i20 from '../../assets/images/20.png';
import i21 from '../../assets/images/21.png';
import i22 from '../../assets/images/22.png';
import i23 from '../../assets/images/23.png';
import i24 from '../../assets/images/24.png';
import i25 from '../../assets/images/25.png';
import i26 from '../../assets/images/26.png';
import i27 from '../../assets/images/27.png';
import i28 from '../../assets/images/28.png';
import i29 from '../../assets/images/29.png';
import i30 from '../../assets/images/30.png';
import i31 from '../../assets/images/31.png';
import i32 from '../../assets/images/32.png';
import i33 from '../../assets/images/33.png';
export const images: string[] = [i0, i1, i2, i3, i4, i5, i6, i7, i8, i9, i10,
    i11, i12, i13, i14, i15,  i16, i17, i18, i19, i20,
    i21, i22, i23, i24, i25, i26, i27, i28, i29, i30, i31, i32, i33];
